- name: install and run nginx #name is not mandatory just give it for your understanding
  hosts: localhost
  become: yes
  tasks: 
  - name: Install nginx
    ansible.builtin.yum: 
      name: nginx
      state: latest
  - name: start nginx
    ansible.builtin.service: 
      name: nginx
      state: started








