- name: install and run nginx #name is not mandatory just give it for your understanding
  hosts: mongodb
  tasks: 
  - name: Install nginx
    ansible.builtin.yum: 
      name: nginx
      state: latest
    ansible.builtin.service: 
      name: nginx
      state: started








