- name: variables from files 
  hosts: local host 
  vars_files: 
  - variables.yaml
  tasks: 
  - name: printing varibles
    ansible.builtin.debug:
    msg: "We are learning {{NAME}}, Duration is {{DURATION}}, Trainer is {{TRAINER}}"
