- name: ansible variables data types
  hosts: localhost
  vars: 
  - AGE: 30 #this is number 
  - NAME: "Nishal" #this is string
  - FeildDevops: True #this is boolean
  - skills: #this is list 
    - DevOps
    - AWS
    - Dynatrace
    - JIRA 
    - SQ
    - NAgios
  - Experience: #this map 
    DevOps: 1
    AWS: 5
    Jira: 3

  tasks: 
  - name: print number variable
    ansible.built.in.debug: 
      msg: "{{AGE}}"

  - name: print string variable
    ansible.built.in.debug: 
      msg: "{{NAME}}"

  - name: print boolean variable 
    ansible.built.in.debug:
      msg: "{{FeildDevops}}"

  - name: print list variables 
    ansible.built.in.debug:
      msg: "{{skills}}"

  - name: print experinece
    ansible.built.in.debug: 
      msg: "{{Experience}}"

