- name: simple condition
  hosts: localhost
  vars: 
    NAME: DevOpsAWS
  
  tasks: 
  - name: run this name is DevOps
    ansible.builtin.debug: 
      msg: "Hello {{NAME}}"
    when: NAME == "DevOps"  #if the above mentioned the name is devops then it will print or else it will skip 

    