- name: install multipackages in ansible 
  hosts: mongodb
  become: yes

  tasks: 
  - name: install packages
    ansible.builtin.yum: 
      name: "{{item}}"
      state: installed

  # - name: start packages
  #   ansible.builtin.service: 
  #     name: "{{item}}"
  #     state: started

    loop: 
    - nginx
    - postmap

    # ansible.builtin.service: 
    #   name: "{{item}}"
    #   state: started